SELECT cash, hours
FROM timesheet
WHERE created_at > CASE
    WHEN EXTRACT(MONTH FROM CURRENT_DATE) <= 2 THEN
        MAKE_DATE(EXTRACT(YEAR FROM CURRENT_DATE) - 1, 1, 31)
    ELSE
        MAKE_DATE(EXTRACT(YEAR FROM CURRENT_DATE), 1, 31)
    END;